---
#- name: "Copy tar"
#  become: true
#  copy:
#    src: artifact.tar.gz
#    dest: $HOME/artifact.tar.gz
#
##- name: "create dir"
##  file:
##    path: $HOME/app
##    state: directory
#
#- name: Creates directory
#  become: true
#  file:
#    path: $HOME/app
#    state: directory
#
#- name: "unarchive tar"
#  become: true
#  unarchive:
#    src: artifact.tar.gz
#    dest: $HOME
#    creates: $HOME/app
#    list_files: yes
#  register: archive_contents
#
##- name: "list dir 2"
##  become: true
##  find:
##    paths: $HOME
##    recurse: yes
#
##- name: "deploy backend"
##  become: true
##  command: "{{ item }}"
##  with_items:
##    - cd $HOME/app
##    - npm install
##    - pm2 stop default
##    - pm2 start npm -- start
#
#- name: "install server"
#  become: true
#  command: npm install
##  args:
##    chdir: $HOME/app
#
#- name: "stop server"
#  become: true
#  command: pm2 stop default
##  args:
##    chdir: $HOME/app
#
#- name: "start server"
#  become: true
#  command: pm2 start npm -- start
##  args:
##    chdir: $HOME/app

- name: "unarchive tar"
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu
    remote_src: no
    mode: 0755

#- name: "list dir"
#  become: yes
#  shell: |
#    ls -la

- name: "run npm install"
  npm:
    path: /home/ubuntu

- name: "start server"
  become: yes
  shell: |
    pm2 stop default || true
    pm2 start npm -- start